
services:
  nginx:
   build: ./nginx/
   ports:
     - "80:80"
   depends_on:
     - nodejs
     - pgadmin
     - postgres
  nodejs:
    build: ./nodejs/
    ports:
      - "8502:81"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: test-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "81:81"







volumes:
  pgdata: {}
